name: Test Secrets Access

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Secret Access
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "GEMINI_API_KEY length: ${#GEMINI_API_KEY}"
          if [ -z "$GEMINI_API_KEY" ]; then
            echo "GEMINI_API_KEY is empty or not set"
          else
            echo "GEMINI_API_KEY is set (first 10 chars): ${GEMINI_API_KEY:0:10}..."
          fi